apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # Name of the object and which group it belongs to.
  name: databaseupdates.kopf.dev
spec:
  # Either Namespaced or Cluster.
  scope: Namespaced
  # API Group.
  # Group name to use for REST API: /apis/<group>/<version>
  group: kopf.dev
  # How to refer to the resource.
  names:
    kind: DatabaseUpdate
    plural: databaseupdates
    singular: databaseupdate
    shortNames:
      - dbupdate
  versions:
    # API Version.
    # List of versions supported by this CustomResourceDefinition.
    - name: v1
      served: true
      storage: true
      # Schema define what a CR should look like.
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # The desired state of the resource. The field is intended to be controlled by the user.
            spec:
              type: object
              properties:
                version:
                  type: string
            # Used by operator to determine the current state of the resource in the cluster.
            status:
              type: object
              properties:
                currentVersion:
                  type: string
      subresources:
        status: {}
